name: blrber
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  # sdk: ">=2.10.5 <3.0.0"
  sdk: ">=2.10.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  # Firebase Plugins
  # firebase_core: ^1.0.1
  # cloud_firestore: ^1.0.1
  # firebase_auth: ^1.0.1
  # firebase_storage: ^8.0.0
  firebase_core: ^0.7.0
  cloud_firestore: ^0.16.0+1
  firebase_auth: 
  firebase_storage: ^7.0.0
  # firebase_messaging: ^6.0.13

  cloud_functions: ^0.9.0

  # Google Plugins
  # google_sign_in: ^5.0.0
  google_sign_in: ^4.5.9

  # Provider Pligins
  provider: ^4.3.3

  # Maps/Location Plugins
  geocoder: ^0.2.1
  geolocator: ^6.2.1
  google_maps_flutter: ^0.5.13
  search_map_place: ^0.3.0

  flag: ^3.2.2

  carousel_slider: ^3.0.0
  photo_view: ^0.11.1
  cached_network_image: ^2.5.1

  badges: ^1.2.0
  

  
  tflite: ^1.1.1
  image_picker: ^0.6.7+22
  # firebase_ml_vision: ^0.11.0
  firebase_ml_custom: ^0.1.0
  
  path_provider: ^1.6.28
  share: 0.6.5+4

  speech_to_text: ^2.3.0

  vin_decoder: ^0.1.3
  custom_radio_grouped_button: any
  flutter_typeahead: ^2.0.0
  currency_pickers: ^1.0.6
  flutter_currency_converter: ^0.0.3
  toggle_switch: ^0.1.9
  flutter_switch: ^0.3.1
  eva_icons_flutter: ^3.0.0
  simple_icons: ^4.24.0
  line_awesome_icons: ^1.0.4+2
  firebase_messaging: ^6.0.13
  search_place_autocomplete: ^0.1.1
  flutter_signin_button: ^2.0.0
  font_awesome_flutter: ^9.0.0
  country_picker: ^2.0.5
  url_launcher:
  darq: ^1.1.1
  money_converter:
  google_ml_vision:

  
  

dev_dependencies:
  flutter_launcher_icons: "^0.8.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/searchBNEW.png"    

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/default_user_image.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
